const dotenv = require("dotenv");

dotenv.config();

const {
  PROD_DATABASE_URI,
  DEV_DATABASE_URI,
  TEST_DATABASE_URI,
  JWTSECRET,
  GCSPROJECTID,
  SENDGRID_API_KEY,
  MAILGUN_API_KEY,
  ORIGIN_DEV,
  ORIGIN_PROD,
} = process.env;

module.exports = {
  PROD_DATABASE_URI,
  DEV_DATABASE_URI,
  TEST_DATABASE_URI,
  JWTSECRET,
  GCSPROJECTID,
  MAILGUN_API_KEY,
  SENDGRID_API_KEY,
  ORIGIN_DEV,
  ORIGIN_PROD,
};
